#!/usr/bin/env sh
if ! head -1 "$1" | grep -qE "^(fix|feat|docs|test|chore|refactor|build|revert|style|perf|ci)(\(.+?\))?: .{1,}$"; then
    echo "Aborting your commit message is invalid" >&2
    exit 1
fi

if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "Aborting your commit message is too long"
    exit 1
fi

